### ISSUE TITLE
Issue Building Dockerfile

### ISSUE THREAD

**Issue by EliCDavis** [allure-framework/allure-docs#115]
![image](https://user-images.githubusercontent.com/9094977/52172080-e295f200-272d-11e9-99d5-d3b6133c817a.png)

Upon cloning your repository I tried to build a docker image using the command

```bash
docker build --tag=allure-docs .
```
and got the following error:

```
Sending build context to Docker daemon  13.55MB
Step 1/3 : FROM nginx:1.12-alpine
1.12-alpine: Pulling from library/nginx
550fe1bea624: Pull complete
af3988949040: Pull complete
d6642feac728: Pull complete
c20f0a205eaa: Pull complete
Digest: sha256:db5acc22920799fe387a903437eb89387607e5b3f63cf0f4472ac182d7bad644
Status: Downloaded newer image for nginx:1.12-alpine
 ---> 24ed1c575f81
Step 2/3 : COPY build/docs/html5 /usr/share/nginx/html
COPY failed: stat /var/lib/docker/tmp/docker-builder908779930/build/docs/html5: no such file or directory
```

**Comment by kostis-codefresh** [comment]
This dockerfile is only packaging the html code, but it doesn't build it itself.

Run first `./gradlew clean build` to create the docs. Then your docker command will succeed

Note: You need a JDK installed locally before you run the gradle command
