### ISSUE TITLE
[Doc][TestNG][v2] Missing allure-testng artefact.

### ISSUE THREAD

**Issue by L-Evg** [allure-framework/allure-docs#36]
The documentation on Allure2-TestNG integration (https://allure-framework.github.io/allure-docs/2.0/#_testng) advises to use io.qameta.allure.allure-testng as a dependency. 
I was not able to get the artefact upon, looks corresponding code is missing in https://github.com/allure-framework/allure2
Expected results: the instruction refers to available artefacts and/or there are steps on how-to get all dependencies (including snapshots).

**Comment by sskorol** [comment]
@L-Evg as you may noticed, there's a `SNAPSHOT` version used in docs. It usually means that it's not published yet. So if you wanna use this new adaptor, you may want to build it manually from sources, or just wait for release.

**Comment by L-Evg** [comment]
@sskorol - thank you, I noticed that. As I stated in the description I have not managed to find that source code in Git repo. Probably it is somewhere around, simply had bas luck with that.

**Comment by sskorol** [comment]
@L-Evg check https://github.com/allure-framework/allure-java

**Comment by L-Evg** [comment]
Thank you!
