### ISSUE TITLE
Jenkins Plugin install issue

### ISSUE THREAD

**Issue by JMoravec** [allure-framework/allure-docs#53]
The [section](https://github.com/allure-framework/allure-docs/blob/master/docs/2.0/reporting/jenkins.adoc#downloading-and-installing-allure-from-archive) about installing Allure to Jenkins from an archive instructs users to download allure-commandline.zip from [Github releases](https://github.com/allure-framework/allure2/releases). however, the latest release with that zip is 2.0-BETA1. Should the install instructions point to [bintray](https://bintray.com/qameta/generic/allure2) instead?

**Comment by eroshenkoam** [comment]
Yep, I will fix it today) 
👍
