### ISSUE TITLE
Unable to locate package allure-commandline

### ISSUE THREAD

**Issue by echoAlexey** [allure-framework/allure-docs#73]
> sudo apt-add-repository ppa:qameta/allure
> sudo apt-get update 
> sudo apt-get install allure-commandline

Executing commands from documentation results in 

> Unable to locate package allure-commandline

**Comment by eroshenkoam** [comment]
I just fixed the docs, so you need to install allure (without commandline postifx).

**Comment by echoAlexey** [comment]
Thank you!
